# -*- coding: utf-8 -*-
"""graduates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iSZePEFXN0W3RlhxYQfuv9u71MmLnN7l
"""

#Pseudocode
# START
# Input var nama,nilai,absen
# IF nilai >= 75 AND absen < 4:
#   print var nama dan "Lulus"
# ELSE:
#   print var nama dan "Tidak Lulus"
# END

nama="Faiz Khansa Adrika"
nilai=90
absen=1

if nilai >= 75 and absen < 4:
  print(nama, "Lulus")
else:
  print(nama, "Tidak Lulus")