# -*- coding: utf-8 -*-
"""grade_mhs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsTV11_IlwA51oXJuRxe9l0JkRAOrcTo
"""

def grade(nama, nilai):
  if nilai < 0 or nilai > 100:
    result = "Nilai Invalid"
  elif nilai >= 80:
    result = "A"
  elif nilai >= 65:
    result = "B"
  elif nilai >= 50:
    result = "C"
  elif nilai >= 35:
    result = "D"
  else:
    result = "E"
  return(nama, result)

print(grade("Faiz Khansa Adrika", 34))

