- name: Menjalankan docker container - Faiz
  hosts: btj-academy
  become: true
  tasks:
    - docker_container:
        name: faiz2
        image: "grad_app"
        interactive: true
        tty: true
        ports:
          - "8024:8024"